[project]
name = "seleniumhttpstatus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.1",
    "seleniumbase>=4.41.1",
]
